# The Docker image that will be used to build your app
image: rust:latest
# Functions that should be executed before the build script is run
before_script:
  - rustup update
  - cargo install --version 0.4.43 mdbook
pages:
  script:
    - mdbook build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - book
  variables:
    PUBLIC_DIR: "book"
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
