stages:
  - deploy

pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl tar
    # 下载并安装 mdBook
    - |
      MDBOOK_VERSION="0.4.43"
      curl -L -o mdbook.tar.gz "https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-musl.tar.gz"
      tar xzf mdbook.tar.gz
      mv mdbook /usr/local/bin/
  script:
    - mdbook build books --dest-dir public
  artifacts:
    paths:
      - public
  only:
    - main