stages:
  - deploy

pages:
  stage: deploy
  image: rust:latest
  variables:
    MD_VERSION: "0.4.43"
  script:
    # 调试：显示目录结构
    - pwd && ls -la

    # 安装mdbook（带版本锁定）
    - cargo install mdbook --vers $MD_VERSION --locked

    # 构建书籍（自动创建public目录）
    - mkdir -p public
    - mdbook build ./ --dest-dir public

    # 调试：验证输出结构
    - echo "生成的文件结构：" && ls -lR public/

    # 路径修正（仅在存在book子目录时执行）
    - |
      if [ -d "public/book" ]; then
        mv public/book/* public/
        rmdir public/book
      fi
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  cache:
    key: mdbook-$CI_COMMIT_REF_SLUG
    paths:
      - /root/.cargo/registry
      - /root/.cargo/git
    policy: pull-push