stages:
  - build
  - deploy

variables:
  MDBOOK_VERSION: "0.4.43"
  PUBLIC_DIR: "public"

# 并发控制（GitLab 15.11+）
workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    - when: manual

build:
  stage: build
  image: rust:latest
  resource_group: pages # 并发控制
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  
  before_script:
    - rustup update
    - cargo install --version $MDBOOK_VERSION mdbook

  script:
    - mdbook build
    - mkdir -p $PUBLIC_DIR
    - cp -r book/* $PUBLIC_DIR/

  artifacts:
    paths:
      - $PUBLIC_DIR
    expire_in: 1 hour

pages:
  stage: deploy
  dependencies:
    - build
  resource_group: pages # 并发控制
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  
  script:
    - echo "Deploying to GitLab Pages..."
    - mv $PUBLIC_DIR ./public

  artifacts:
    paths:
      - public