# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/

[book]
authors             = ["Billy"]
language            = "zh"
src                 = "books"
title               = "Billyの个人博客"

[build]
build-dir = "public"

[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/lipeilin375"
edit-url-template = "https://github.com/lipeilin375/lipeilin375.github.io/edit/main/{path}"

[output.html.print]
enable = true
page-break = true

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true
runnable = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]