name: Ask for content
description: If you have anything want to study, we're welcome you to tell us here.
labels: ["Content"]
body:
  - type: markdown
    id: detail
    attibutes:
      label: Details
      description: >
        Tell us more detail about what you want to study.
      validations:
        required: true