name: Sync to GitLab

on:
  push:
    branches:
      - main  # 根据你的需求设置为合适的分支，如 'main' 或 'master'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for GitLab
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - name: Pull latest changes from GitLab
      run: |
        git remote add gitlab git@gitlab.com:lipeilin3751/lipeilin3751.gitlab.io.git
        git fetch gitlab
        git pull gitlab main

    - name: Push to GitLab
      run: |
        git remote add gitlab git@gitlab.com:lipeilin3751/lipeilin3751.gitlab.io.git
        git push --all gitlab