name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Configure Git
      run: |
        git config --global user.name "Auto Sync"
        git config --global user.email "no-reply@auto.sync.com"

    - name: Setup SSH
      run: |
        # 安装SSH密钥
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # 将GitLab加入已知主机
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - name: Add GitLab Remote
      run: |
        git remote add gitlab git@gitlab.com:lipeilin3751/lipeilin3751.gitlab.io.git

    - name: Push to GitLab
      run: |
        git push --force --mirror gitlab