name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Configure Git
      run: |
        git config --global user.name "Auto Sync"
        git config --global user.email "no-reply@auto.sync.com"

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - name: Add GitLab Remote
      run: |
        git remote add gitlab git@gitlab.com:lipeilin3751/lipeilin3751.gitlab.io.git

    - name: Purge remote-tracking refs
      run: |
        # 删除所有远程跟踪分支（origin/*）
        git for-each-ref --format='delete %(refname)' refs/remotes | git update-ref --stdin

    - name: Push to GitLab
      run: |
        # 仅推送本地分支和标签
        git push gitlab --force refs/heads/*:refs/heads/*
        git push gitlab --tags --force