name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for GitLab
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    - name: Fetch latest commits from GitLab
      run: |
        # 检查是否已经添加了远程仓库，如果没有则添加
        git remote get-url gitlab || git remote add gitlab git@gitlab.com:lipeilin3751/lipeilin3751.gitlab.io.git
        git fetch gitlab

    - name: Push to GitLab
      run: |
        # 检查是否已经添加了远程仓库，如果没有则添加
        git remote get-url gitlab || git remote add gitlab git@gitlab.com:lipeilin3751/lipeilin3751.gitlab.io.git
        git push --all gitlab
